<?php
namespace App\Http\Controllers\Voyager;

use Illuminate\Http\Request;
use TCG\Voyager\Http\Controllers\VoyagerBaseController;

class RestaurantController extends VoyagerBaseController {

    public function index(Request $request)
    {
        return parent::index($request); // TODO: Change the autogenerated stub

    }

}
